version: '3'
services:
  django:
    build:
      context: ./django-autorecruiting-app
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - ./django-autorecruiting-app:/app

  flask:
    build:
      context: ./hh-server
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    volumes:
      - ./hh-server:/app
